logging.level.guru: debug

server.port: 8082

spring:
    application:
        name: inventory-service
    artemis:
        user: artemis
        password: simetraehcapa
    zipkin:
        enabled: false

logging:
    level:
        guru.sfg: debug

eureka:
    client:
        serviceUrl:
            #            default value + 'netflix' is an username and 'eureka' is a password via base authentication
            defaultZone: http://netflix:eureka@localhost:8761/eureka