logging.level.guru: debug

server.port: 8082

spring:
    application:
        name: inventory-service
    artemis:
        user: artemis
        password: simetraehcapa
    zipkin:
        base-url: http://localhost:9411/

logging:
    level:
        guru.sfg: debug

eureka:
    client:
        serviceUrl:
            #            default value
            defaultZone: http://localhost:8761/eureka