spring:
    datasource:
        username: beer_inventory_service
        password: password
        url: jdbc:mysql://127.0.0.1:3306/beer_inventory_service_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    cloud:
        discovery:
            #disable service discovery
            enabled: false
logging:
    level:
#        org.hibernate:
#            SQL: DEBUG
#            type.descriptor.sql.BasicBinder: TRACE
        com.zaxxer.hikari:
            HikariConfig: TRACE
