logging.level.guru: debug

server.port: 8082

spring:
    application:
        name: inventory-service
    artemis:
        user: artemis
        password: simetraehcapa
    zipkin:
        enabled: false
    security:
        user:
#            should be env property
            name: good
            password: beer

logging:
    level:
        guru.sfg: debug
